# These are supported funding model platforms

github: [Harikrishna-Srinivasan] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# open_collective: # Replace with a single Open Collective username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
# thanks_dev: # Replace with a single thanks.dev username
custom: [harikrishnasri3@okicici] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
